version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - VITE_PORT=${VITE_PORT:-5173}
      - VITE_APP_BACKEND_ADDRESS=${VITE_APP_BACKEND_ADDRESS}
    command: npm run dev
