version: 2
updates:
  # Check for npm dependency updates (package.json)
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - piyushsharma919
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Optional: Check for GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
